version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/services/langfuse-web"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
    groups:
      patch-minor:
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "docker"
    directory: "/services/langfuse-worker"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
    groups:
      patch-minor:
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "docker"
    directory: "/services/minio"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
    groups:
      patch-minor:
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "docker"
    directory: "/services/postgres"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
    groups:
      patch-minor:
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "docker"
    directory: "/services/redis"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
    groups:
      patch-minor:
        update-types:
          - "patch"
          - "minor"
